# Site settings
title: AIRouting
email: info@cmlteam.com
description: > # this means to ignore newlines until "baseurl:"
  AIRouting - Recommendation engine to route debit/credit card payments to payment service provider (PSP) in a most efficient way in terms of acceptance rate and fees paid
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://airouting.cmlteam.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

cml_site: "https://www.cmlteam.com"

# Build settings
markdown: kramdown
